sudo: required

# This moves Kubernetes specific config files.
env:
- CHANGE_MINIKUBE_NONE_USER=true

before_script:
- travis_setup/minikube.sh

jobs:
  include:
  - script:
    - kubectl apply -f guestbook.yaml
    - curl $(minikube service frontend --url) | grep -q "<title>Guestbook</title>"
  - script:
    - kubectl apply -f kubectl/cats-guestbook.yaml
    - kubectl apply -f kubectl/dogs-guestbook.yaml
    - curl $(minikube service cats-frontend --url) | grep -q "<title>Guestbook</title>"
    - curl $(minikube service dogs-frontend --url) | grep -q "<title>Guestbook</title>"
  - script:
    - travis_setup/helm.sh
    - helm init --wait
    - helm install -f helm/cats.yaml helm/guestbook
    - helm install -f helm/dogs.yaml helm/guestbook
    - curl $(minikube service cats-frontend --url) | grep -q "<title>Guestbook</title>"
    - curl $(minikube service dogs-frontend --url) | grep -q "<title>Guestbook</title>"